### ISSUE TITLE
Correction de typo! 

### ISSUE THREAD

**Issue by odyright** [RemyCedric/gestion-de-projet#1]
https://github.com/RemyCedric/gestion-de-projet/blob/master/CasterStats.Web.Angular5/src/app/main/content/pages/users/_services/user.service.ts#L39

```saveUser(user) {
    return new Promise((resolve, reject) => {
      this.http.post('api/e-commerce-products/' + user.id, user)
        .subscribe((response: any) => {
          resolve(response);
        }, reject);
    });
}
```
**api/e-commerce-products/** devrait être autre chose que product!

**Comment by RemyCedric** [comment]
c'est du copier coller pour des test la méthode save n'est pas encore utilisée le code est resté de base

**Comment by odyright** [comment]
No problème bro
